### ISSUE TITLE
Update Footer Contact Us

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#11]
Once issue #10 is resolved, we can update the website footer to reference hello@phonegap.com.

**Comment by GarthDB** [comment]
So we should just put the email address and link it to hello@phonegap.com ?

I don't think it should go in the list of links. Do you have a recommendation @jahoni?

![image](https://cloud.githubusercontent.com/assets/125516/11198945/4a44dc22-8c86-11e5-971b-ccd15e1b1cae.png)

**Comment by jahoni** [comment]
I was the one that proposed having the contact us link send an email. I'm still good with that. 

Why don't you like it @GarthDB ? Because it is not like the other links? Because you don't think people should/will contact us? Because the label isn't accurate? What if it said "Email Us" instead? 

I'm not keen on the idea of setting up a contact form, and we don't have any other methods of contact (unless we just forward phone calls to Steve Gill...he'd love that).

**Comment by GarthDB** [comment]
@jahoni I'm fine not having a contact form - I prefer an email link, but the rest of the links in the list go to new pages. "Email Us" would be better I think. Does that mean we'll no longer have a contact page?

Is there information on the current [contact page](http://phonegap.com/about/contact/) we would miss?

**Comment by jahoni** [comment]
Cool. I'm down with changing the label to "Email Us". I'll update the detailed IA spreadsheet to reflect that, but not mock-ups, if that is okay with you @GarthDB.

Yup - the plan has been to get rid of the contact us page on the new site.

**Comment by GarthDB** [comment]
Sounds good.
