### ISSUE TITLE
Add Google Analytics to site for launch

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#75]
- [x] [phonegap.github.io and blog](https://github.com/phonegap/phonegap.github.io)
- [x] [docs.phonegap.com](https://github.com/phonegap/phonegap-docs)
- [ ] [phonegap.com/app](https://github.com/phonegap/app)
- [ ] phonegap.com/book (not yet active)
- [ ] phonegap.com/tool (not yet active)
- [ ] phonegap.com/events (not yet active)

**Comment by GarthDB** [comment]
Current google analytic code:
```html
<script type="text/javascript">

     var _gaq = _gaq || [];
     _gaq.push(['_setAccount', 'UA-94271-11']);
     _gaq.push(['_setDomainName', 'phonegap.com']);
     _gaq.push(['_trackPageview']);

     (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

</script>
```

Updated code
```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-94271-11', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by mwbrooks** [comment]
Definitely using Universal Analytics is an improvement, but I think we need to take the above snippet a little further.

We try to share one GA tracking cookie for all PG properties. Some of our PG properties still use the legacy Google Analytics tracker, while others use the new Universal Analytics. GA Universal can support the legacy cookie, but you need to explicitly tell it the `legacyCookieDomain` to use. Additionally, we want to resolve all the new Universal Analytics tracking cookies to one domain (phonegap.com), so we must explicitly state the domain instead of using `auto`. I believe this snippet is correct:

```javascript
<script type="text/javascript">(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-94271-11', {
  cookieDomain: 'phonegap.com',
  legacyCookieDomain: 'phonegap.com'
});
ga('send', 'pageview');</script>
```

**Comment by GarthDB** [comment]
Thanks! I'm was just going off what google was giving me. It's nice you've put more thought into it.
